In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [9]:
%%time
df = pd.read_csv('diabetic_data.csv')

CPU times: user 300 ms, sys: 35.6 ms, total: 336 ms
Wall time: 334 ms

In [6]:
df.head()

,encounter_id,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,None,None,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,NO
1,149190,None,None,No,No,No,No,No,No,No,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,None,None,No,No,No,No,No,No,Steady,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,None,None,No,No,No,No,No,No,No,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,None,None,No,No,No,No,No,No,Steady,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [7]:
df.tail()

,encounter_id,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,acetohexamide,glipizide,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
101761,443847548,None,>8,Steady,No,No,No,No,No,No,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,None,None,No,No,No,No,No,No,No,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,None,None,Steady,No,No,No,No,No,No,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,None,None,No,No,No,No,No,No,Steady,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,None,None,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,NO

In [8]:
df.shape

(101766, 29)